### ISSUE TITLE
Can/Should this be usable on a multisite install?

### ISSUE THREAD

**Issue by HersamAcornMedia** [pathawks/Export-to-InDesign#4]
We are running Wordpress 4.1 and get this error:
 <br />
<b>Fatal error</b>:  Call to undefined function mb_convert_encoding() in <b>/var/www/hanewsmedia.com/wp-content/plugins/dirty-suds-export-to-indesign/taggedtext.php</b> on line <b>414</b><br />

Am hopeful there's a fix.
Thanks

**Comment by pathawks** [comment]
[`mb_convert_encoding`](http://php.net/manual/en/function.mb-convert-encoding.php) is a standard PHP function.
