### ISSUE TITLE
Export with Classic Mac (CR) line breaks?

### ISSUE THREAD

**Issue by lexpressto** [pathawks/Export-to-InDesign#6]
Could you please provide the code for changing the line break to CR?
We have to open the export with Text Wrangler change from Windows (CFLR) to Classic Mac (CR) each time.

Thanks for the plugin!

**Comment by pathawks** [comment]
Change the output format to `ANSI-Mac` in settings.

**Comment by lexpressto** [comment]
Hmmm, the text is outputting to ANSI-Mac 
Here's an example of the exported text:
[Resch-p72511.txt](https://github.com/pathawks/Export-to-InDesign/files/358052/Resch-p72511.txt)
If it's something odd or a single use issue, I'll keep on looking around.
Regards

**Comment by pathawks** [comment]
I _may_ have found the problem.

Can you try [this version](https://github.com/pathawks/Export-to-InDesign/files/358123/Export-to-InDesign-defaults.zip) (from the [`defaults` branch](https://github.com/pathawks/Export-to-InDesign/tree/defaults)) and let me know if it solves the issue?

**Comment by lexpressto** [comment]
@pathawks It works! Thank you very much.
